src/Web/Controllers/BoardsController.cs
using AutoMapper;
using DataModels.Models.Board;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.BoardColumns;
using Services.BurndownDatas;
using Services.Projects;
using Services.Sprints;
using Services.WorkItems.Bugs;
using Services.WorkItems.Tasks;
using Services.WorkItems.Tests;
using Services.WorkItems.UserStories;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Web.Controllers
{
    [Authorize]
    public class BoardsController : BaseController
    {
        private readonly IMapper mapper;
        private readonly IBoardsService boardColumnsService;
        private readonly ISprintsService sprintsService;
        private readonly IUserStoryService userStoryService;
        private readonly ITestsService testsService;
        private readonly ITasksService tasksService;
        private readonly IBugsService bugsService;
        private readonly IBurndownDataService burndownDataService;

        public BoardsController(IMapper mapper,
            IProjectsService projectsService,
            IBoardsService boardColumnsService,
            ISprintsService sprintsService,
            IUserStoryService userStoryService,
            ITestsService testsService,
            ITasksService tasksService,
            IBugsService bugsService,
            IBurndownDataService burndownDataService)
            : base(projectsService)
        {
            this.mapper = mapper;
            this.boardColumnsService = boardColumnsService;
            this.sprintsService = sprintsService;
            this.userStoryService = userStoryService;
            this.testsService = testsService;
            this.tasksService = tasksService;
            this.bugsService = bugsService;
            this.burndownDataService = burndownDataService;
        }

        public async Task<IActionResult> Board(int projectId, int sprintId)
        {
            if (!this.IsCurrentUserInProject(projectId))
            {
                return Unauthorized();
            }

            var boardViewModel = new BoardColumnAllViewModel()
            {
                BoardColumnAllDto = await this.boardColumnsService.GetAllColumnsAsync(projectId, sprintId),
                SprintDropDown = await this.sprintsService.GetSprintDropDownAsync(projectId),
                OldSprintBurnDownIds = await this.sprintsService.GetOldSprintBurndownData(projectId),
            };

            return View(boardViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> ChangeColumn(int columnId, int itemId, bool isUserStory, bool isTask, bool isTest, bool isBug)
        {
            if (isUserStory)
            {
                await this.userStoryService.ChangeColumnAsync(itemId, columnId);
            }
            else if (isTask)
            {
                await this.tasksService.ChangeColumnAsync(itemId, columnId);
            }
            else if (isTest)
            {
                await this.testsService.ChangeColumnAsync(itemId, columnId);
            }
            else if (isBug)
            {
                await this.bugsService.ChangeColumnAsync(itemId, columnId);
            }

            return Json(new { changed = "changed" });
        }

        public async Task<IActionResult> Options(int projectId)
        {
            if (!this.IsCurrentUserInProject(projectId))
            {
                return Unauthorized();
            }

            var alreadyBoard = await this.boardColumnsService.GetColumnOptionsAsync(projectId);

            var board = new BoardOptionsInputModel()
            {
                AlreadyColumns = alreadyBoard,
            };

            return View(board);
        }

        [HttpPost]
        public async Task<IActionResult> AddColumn(int projectId, BoardOptionsInputModel inputModel)
        {
            if (!this.IsCurrentUserInProject(projectId))
            {
                return Unauthorized();
            }

            await this.boardColumnsService.AddcolumnToTheLeftAsync(inputModel);

            return RedirectToAction(nameof(Options), new { projectId = projectId });
        }

        public IActionResult Burndown()
        {
            return View();
        }

        public async Task<IActionResult> GetBurndownData(int projectId, int sprintId)
        {
            try
            {
                var viewModel = await this.boardColumnsService.GetBurndownData(projectId, sprintId);
                viewModel.Velocity = await this.sprintsService.GetVelocityAsync(projectId, sprintId);

                return Json(new { DaysInSprint = viewModel.DaysInSprint, ScopeChanges = viewModel.ScopeChanges, 
                    TasksRemaining = viewModel.TasksRemaining, Velocity = viewModel.Velocity });
            }
            catch
            {
                return RedirectToAction("Error", "Error");
            }
        }
    }
}

src/Web/Controllers/ProjectsController.cs
using AutoMapper;
using DataModels.Models.Error;
using DataModels.Models.Projects;
using DataModels.Models.TeamRoles;
using DataModels.Models.Users;
using DataModels.Pagination;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Projects;
using Services.TeamRoles;
using Shared.Constants;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using Web.Extentions;
using Web.Helpers;

namespace Web.Controllers
{
    [Authorize]
    public class ProjectsController : BaseController
    {
        private readonly IProjectsService projectsService;
        private readonly IMapper mapper;
        private readonly ITeamRolesService teamRolesService;

        public ProjectsController(IProjectsService projectsService,
            IMapper mapper,
            ITeamRolesService teamRolesService) : base(projectsService)
        {
            this.projectsService = projectsService;
            this.mapper = mapper;
            this.teamRolesService = teamRolesService;
        }

        public async Task<IActionResult> Get(int projectId)
        {
            if (!IsCurrentUserInProject(projectId))
            {
                return Unauthorized();
            }

            var project = mapper.Map<ProjectViewModel>(await this.projectsService.GetAsync(projectId));

            return View(project);
        }

        public async Task<IActionResult> AddUserToProject(int projectId)
        {
            if (!IsCurrentUserInProject(projectId))
            {
                return Unauthorized();
            }

            var AddUserToProjectInputModel = new AddUserToProjectInputModel
            {
                UsersDropdown = this.mapper.Map<ICollection<UsersDropdown>>(await this.projectsService.GetUsersDropDown(projectId)),
            };

            return View(AddUserToProjectInputModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddUserToProject(AddUserToProjectInputModel inputModel, int projectId)
        {
            if (!IsCurrentUserInProject(projectId))
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
            {
                var AddUserToProjectInputModel = new AddUserToProjectInputModel
                {
                    UsersDropdown = this.mapper.Map<ICollection<UsersDropdown>>(await this.projectsService.GetUsersDropDown(projectId)),
                };
            }

            await this.projectsService.AddUserToProject(inputModel.UserId, projectId);

            return RedirectToAction(nameof(Get), new { projectId = projectId });
        }

        public async Task<IActionResult> GetAll(PaginationFilter paginationFilter)
        {
            var userId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var paginatedViewModel = this.mapper.Map<PaginatedProjectViewModel>
                (await this.projectsService.GetAllAsync(userId, paginationFilter));

            return View(paginatedViewModel);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateProjectInputModel createInputModel, PaginationFilter paginationFilter)
        {
            bool isValid;
            string responseHtml;

            if (!ModelState.IsValid)
            {
                isValid = false;
                responseHtml = await this.RenderViewAsStringAsync("Create", createInputModel, true);
                return Json(new { isValid = isValid, html = responseHtml });
            }

            if (this.projectsService.IsNameTaken(createInputModel.Name))
            {
                ModelState.AddModelError(string.Empty, $"The project '{createInputModel.Name}' already exists.");
                isValid = false;
                responseHtml = await this.RenderViewAsStringAsync("Create", createInputModel, true);
                return Json(new { isValid = isValid, html = responseHtml });
            }

            try
            {
                var userId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
                await this.projectsService.CreateAsync(createInputModel, userId);

                var responseModel = this.mapper.Map<PaginatedProjectViewModel>
                    (await this.projectsService.GetAllAsync(userId, paginationFilter));

                isValid = true;
                responseHtml = await this.RenderViewAsStringAsync("_ViewAll", responseModel, false);
            }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, ErrorConstants.ContactSupportMessage);
                isValid = false;
                responseHtml = await this.RenderViewAsStringAsync("Create", createInputModel, true);
            }

            return Json(new { isValid = isValid, html = responseHtml });
        }

        public async Task<IActionResult> Edit(int projectId)
        {
            // If projectId does not exist or user has no ref to the project.
            if (!IsCurrentUserInProject(projectId))
            {
                return Unauthorized();
            }

            var project = mapper.Map<EditProjectInputModel>(await this.projectsService.GetAsync(projectId));
            var responseHtml = await this.RenderViewAsStringAsync("Edit", project);

            return Json(new { html = responseHtml });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditProjectInputModel editModel)
        {
            bool isValid;

            // If projectId does not exist or user has no ref to the project.
            if (!IsCurrentUserInProject(editModel.ProjectId))
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
            {
                isValid = false;
                var responseHtml = await this.RenderViewAsStringAsync("Edit", editModel, true);
                return Json(new { isValid = isValid, html = responseHtml });
            }

            try
            {
                await this.projectsService.UpdateAsync(editModel);
                isValid = true;

                return Json(new { isValid = isValid, newDescription = editModel.Description });
            }
            catch (Exception)
            {
                this.ModelState.AddModelError(string.Empty, ErrorConstants.ContactSupportMessage);
                isValid = false;

                return Json(new { isValid = isValid, newDescription = editModel.Description });
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int projectId)
        {
            // If projectId does not exist or user has no ref to the project.
            if (!IsCurrentUserInProject(projectId))
            {
                return Unauthorized();
            }

            try
            {
                await this.projectsService.DeleteAsync(projectId);
                return RedirectToAction(nameof(GetAll), new PaginationFilter());
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Error");
            }
        }

        [HttpPost]
        public async Task<IActionResult> RemoveUserFromProject(int userId, int projectId)
        {
            if (!this.IsCurrentUserInProject(projectId))
            {
                return Unauthorized();
            }

            if (await this.projectsService.IsLastUserInProjectAsync(userId, projectId))
            {
                TempData["RemoveError"] = "Last user in project cannot be removed!";

                return RedirectToAction(nameof(Get), new { projectId = projectId });
            }

            try
            {
                await this.projectsService.RemoveUserFromProjectAsync(userId, projectId);
                TempData["RemoveSuccess"] = "You removed " + this.User.FindFirstValue(ClaimTypes.Email) + " from project";

                return RedirectToAction(nameof(Get), new { projectId = projectId });
            }
            catch
            {
                return RedirectToAction("Error", "Error");
            }
        }
    }
}

src/Web/Controllers/SprintsController.cs
using AutoMapper;
using DataModels.Models.Sprints;
using DataModels.Models.Sprints.Dto;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Projects;
using Services.Sprints;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Threading.Tasks;

namespace Web.Controllers
{
    [Authorize]
    public class SprintsController : BaseController
    {
        private readonly ISprintsService sprintsService;
        private readonly IMapper mapper;

        public SprintsController(ISprintsService sprintsService,
            IProjectsService projectsService,
            IMapper mapper)
            : base(projectsService)
        {
            this.sprintsService = sprintsService;
            this.mapper = mapper;
        }

        public async Task<IActionResult> All(int projectId)
        {
            if (!this.IsCurrentUserInProject(projectId))
            {
                return Unauthorized();
            }

            var sprintsViewModel = this.mapper.Map<ICollection<SprintAllViewModel>>
                (await this.sprintsService.GetAllForProjectAsync(projectId));

            return View(sprintsViewModel);
        }

        public IActionResult Create(int projectId)
        {
            if (!this.IsCurrentUserInProject(projectId))
            {
                return Unauthorized();
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(int projectId, SprintInputModel inputModel)
        {
            if (!this.IsCurrentUserInProject(projectId))
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
            {
                return View(inputModel);
            }

            try
            {
                if (DateTime.Compare(inputModel.ParsedStartDate, inputModel.ParsedDueDate) > 0)
                {
                    this.ModelState.AddModelError(string.Empty, "Start date cannot be earlier than end date.");

                    return View(inputModel);
                }

                var inputDto = this.mapper.Map<SprintInputDto>(inputModel);
                inputDto.ProjectId = projectId;
                inputDto.StartDate = inputModel.ParsedStartDate;
                inputDto.DueDate = inputModel.ParsedDueDate;

                await this.sprintsService.CreateSprintAsync(inputDto);
                TempData["SprintSuccess"] = $"Successfully created sprint: {inputModel.Name}.";

                return RedirectToAction(nameof(All), new { projectId = projectId });
            }
            catch
            {
                return RedirectToAction("Error", "Error");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int projectId, int sprintId, string sprintName)
        {
            //TODO enable delete only if team member is project manager or scrum master
            if (!this.IsCurrentUserInProject(projectId))
            {
                return Unauthorized();
            }

            if (!await this.sprintsService.AreUserStoriesInSprintAsync(sprintId))
            {
                try
                {
                    await this.sprintsService.DeleteAsync(sprintId);
                    TempData["SprintSuccess"] = $"Sprint {sprintName} was successfully deleted.";

                    return RedirectToAction(nameof(All), new { projectId = projectId });
                }
                catch 
                {
                    return RedirectToAction("Error", "Error");
                }
            }

            TempData["SprintDeleteError"] = "Sprint with assigned user stories cannot be deleted.";

            return RedirectToAction(nameof(All), new { projectId = projectId });
        }
    }
}

src/Web/Views/Shared/Partials/_LeftNavPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Data.Models.Users
@inject SignInManager<User> SignInManager

@if (SignInManager.IsSignedIn(User) && Url.ActionContext.RouteData.Values["projectId"] != null)
{
    <div id="mySidenav" class="sidenav">
        <a asp-area="Wiki" asp-action="Index" asp-controller="Home" 
           asp-route-projectId="@this.ViewContext.RouteData.Values["projectId"]">
            Wiki
        </a>
        <a class="nav-link" asp-area="" asp-controller="WorkItems"
           asp-action="GetAll" asp-route-projectId="@this.ViewContext.RouteData.Values["projectId"]">
            Work Items
        </a>
        <a asp-area="" asp-controller="Boards"
           asp-action="Board" asp-route-projectId="@this.ViewContext.RouteData.Values["projectId"]">
            Board
        </a>
        <a asp-area="" asp-controller="Sprints"
           asp-action="All" asp-route-projectId="@this.ViewContext.RouteData.Values["projectId"]">
            Sprints
        </a>
    </div>
}

src/Web/Views/Shared/Partials/_PaginationPartial.cshtml
@{
    string pageNumber = Context.Request.Query["PageNumber"].ToString();
    int currentPage = String.IsNullOrEmpty(pageNumber) ? 1 : int.Parse(pageNumber);
}

<div>
    <nav aria-label="Page navigation example">
        <ul class="pagination" style="justify-content: center;">
            @if (currentPage > 2)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="GetAll" asp-route-PageNumber="1" aria-label="First">
                        <span aria-hidden="true">&laquo;&laquo;</span>
                        <span class="sr-only"></span>
                    </a>
                </li>
            }
            @if (currentPage == 1)
            {
                <li class="page-item disabled">
                    <a class="page-link" asp-action="GetAll" asp-route-PageNumber="@(currentPage - 1)" aria-label="First">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link" asp-action="GetAll" asp-route-PageNumber="@(currentPage - 1)" aria-label="First">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
            }
            @if (currentPage > 2)
            {
                <li class="page-item disabled">
                    <a class="page-link">
                        ...
                    </a>
                </li>
            }
            @for (int i = currentPage; i < currentPage + 3; i++)
            {
                if ((i - 1 != 0) ^ (i - 1 > Model.TotalPages))
                {
                    if (i - 1 == currentPage)
                    {
                        <li class="page-item disabled">
                            <a class="page-link" asp-action="GetAll" asp-route-PageNumber="@(i - 1)">
                                @(i - 1)
                            </a>
                        </li>
                    }
                    else
                    {
                        <li class="page-item">
                            <a class="page-link" asp-action="GetAll" asp-route-PageNumber="@(i - 1)">
                                @(i - 1)
                            </a>
                        </li>
                    }
                }
            }
            @if (currentPage + 1 < Model.TotalPages)
            {
                <li class="page-item disabled">
                    <a class="page-link">
                        ...
                    </a>
                </li>
            }
            @if (currentPage == Model.TotalPages)
            {
                <li class="page-item disabled">
                    <a class="page-link" asp-action="GetAll" asp-route-PageNumber="@(currentPage + 1)" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link" asp-action="GetAll" asp-route-PageNumber="@(currentPage + 1)" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            }
            @if (currentPage + 1 < Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-action="GetAll" asp-route-PageNumber="@Model.TotalPages" aria-label="Next">
                        <span aria-hidden="true">&raquo;&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            }

        </ul>
    </nav>
</div>

src/Web/Views/Shared/Partials/_TopNavPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Data.Models.Users
@using Shared.Constants;
@inject SignInManager<User> SignInManager

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 fixed-top">
    @* If user has signed in and projecd has beed selected *@
    @if (SignInManager.IsSignedIn(User) && Url.ActionContext.RouteData.Values["projectId"] != null)
    {
        <div class="container" id="left-nav-buttton">
            <a href="" class="navbar-brand open-nav" onclick="openNav()" style="margin-left:-10px; display:none;">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-toggle-off" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M11 4a4 4 0 0 1 0 8H8a4.992 4.992 0 0 0 2-4 4.992 4.992 0 0 0-2-4h3zm-6 8a4 4 0 1 1 0-8 4 4 0 0 1 0 8zM0 8a5 5 0 0 0 5 5h6a5 5 0 0 0 0-10H5a5 5 0 0 0-5 5z" />
                </svg>
            </a>
            <a href="" class="close-nav navbar-brand" onclick="closeNav()" style="margin-left:-10px; display:none">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-toggle-on" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M5 3a5 5 0 0 0 0 10h6a5 5 0 0 0 0-10H5zm6 9a4 4 0 1 0 0-8 4 4 0 0 0 0 8z" />
                </svg>
            </a>
        </div>
    }
    <div class="container" id="top-nav-container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-house" fill="currentColor" xmlns="http://www.w3.org/2000/svg" style=" font-size: 1.4rem; margin-bottom: 0.3rem;">
                <path fill-rule="evenodd" d="M2 13.5V7h1v6.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z" />
                <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z" />
            </svg>AgileMS
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <partial name="_LoginPartial" />

            @if (SignInManager.IsSignedIn(User))
            {
                @await Component.InvokeAsync("Notifications", new { userId = int.Parse(SignInManager.UserManager.GetUserId(User)) })

                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="GetAll">Projects</a>
                    </li>
                    @if (SignInManager.IsSignedIn(User) && User.IsInRole(ApplicationRolesConstatnts.Admin))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="https://localhost:5001/hangfire">
                                hangfire
                            </a>
                        </li>
                    }
                </ul>
            }
        </div>
    </div>
</nav>