src/Web/Controllers/CommentsController.cs
using AutoMapper;
using DataModels.Models.Comments;
using DataModels.Models.Comments.Dtos;
using Microsoft.AspNetCore.Mvc;
using Services.Comments;
using System.Security.Claims;
using System.Threading.Tasks;
using Web.Extentions;
using Web.Helpers;

namespace Web.Controllers
{
    public class CommentsController : BaseController
    {
        private readonly ICommentsService commentsService;
        private readonly IMapper mapper;

        public CommentsController(ICommentsService commentsService,
            IMapper mapper)
        {
            this.commentsService = commentsService;
            this.mapper = mapper;
        }

        [NoDirectAccess]
        public async Task<IActionResult> Edit(int commentId)
        {
            var commentViewModel = this.mapper.Map<CommentViewModel>
                (await this.commentsService.GetAsync(commentId));

            return Json(new { html = await this.RenderViewAsStringAsync(nameof(Edit), commentViewModel, true) });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int projectId, CommentInputModel model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }

            if(!IsUsersComment(model.Id))
            {
                return Unauthorized();
            }

            var updateModel = this.mapper.Map<CommentsUpdateModel>(model);
            await this.commentsService.UpdateAsync(updateModel);
            var updated = await this.commentsService.GetAsync(model.Id);

            return RedirectToAction(nameof(WorkItemsController.GetUserStory), "WorkItems", new { ProjectId = projectId, workItemId = updated.WorkItemId });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int projectId, int commentId, int workItemId)
        {
            if (!IsUsersComment(commentId))
            {
                return Unauthorized();
            }

            await this.commentsService.DeleteAsync(commentId);

            return RedirectToAction(nameof(WorkItemsController.GetUserStory), "WorkItems", new { projectId = projectId, workItemId = workItemId });
        }
        
        private bool IsUsersComment(int commentId)
        {
            var userId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            return this.commentsService.IsUsersComment(userId, commentId);
        }
    }
}

src/Web/Controllers/UserStoriesController.cs
using AutoMapper;
using DataModels.Models.Sorting;
using DataModels.Models.UserStories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.BacklogPriorities;
using Services.Projects;
using Services.UserStories;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Web.Controllers
{
    [Authorize]
    public class UserStoriesController : BaseController
    {
        private readonly IUserStoriesService userStoriesService;
        private readonly IBacklogPrioritiesService backlogPrioritiesService;
        private readonly IMapper mapper;

        public UserStoriesController(IUserStoriesService userStoriesService,
            IBacklogPrioritiesService backlogPrioritiesService,
            IProjectsService projectsService,
            IMapper mapper) : base(projectsService)
        {
            this.userStoriesService = userStoriesService;
            this.backlogPrioritiesService = backlogPrioritiesService;
            this.mapper = mapper;
        }

        public async Task<IActionResult> Index(int projectId, SortingFilter sortingFilter)
        {
            if (!IsUserInProject(projectId))
            {
                return Unauthorized();
            }
            
            var all = this.mapper.Map<IEnumerable<UserStoriesAllViewModel>>
                (await userStoriesService.GetAllAsync(projectId, sortingFilter));

            return View(all);
        }

        public async Task<IActionResult> Create(int projectId)
        {
            if (!IsUserInProject(projectId))
            {
                return Unauthorized();
            }

            var createViewModel = new UserStoryInputModel()
            {
                PrioritiesDropDown = this.mapper.Map<ICollection<BacklogPriorityDropDownModel>>
                (await this.backlogPrioritiesService.GetAllAsync())
            };

            return View(createViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(UserStoryInputModel inputModel, int projectId)
        {
            if (!IsUserInProject(projectId))
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
            {
                inputModel.PrioritiesDropDown = this.mapper.Map<ICollection<BacklogPriorityDropDownModel>>
                    (await this.backlogPrioritiesService.GetAllAsync());
                return View(inputModel);
            }

            await this.userStoriesService.CreateAsync(inputModel);
            return RedirectToAction("Index", new { projectId = projectId });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int projectId, int userStoryId)
        {
            if (!IsUserInProject(projectId))
            {
                return Unauthorized();
            }

            await this.userStoriesService.DeleteAsync(userStoryId);

            return RedirectToAction("Index", new { projectId = projectId });
        }

        public async Task<IActionResult> Get(int projectId, int userStoryId)
        {
            if (!IsUserInProject(projectId))
            {
                return Unauthorized();
            }

            var userStory = new UpdateUserStoriesViewModel()
            {
                PrioritiesDropDown = this.mapper.Map<ICollection<BacklogPriorityDropDownModel>>
                    (await this.backlogPrioritiesService.GetAllAsync()),
                ViewModel = this.mapper.Map<UserStoryViewModel>(await userStoriesService.GetAsync(userStoryId))
            };

            if (userStory.ViewModel == null)
            {
                return NotFound();
            }

            return View(userStory);
        }

        [HttpPost]
        public async Task<IActionResult> Get(UpdateUserStoriesViewModel model, int projectId)
        {
            if (!IsUserInProject(projectId))
            {
                return Unauthorized();
            }

            if (!ModelState.IsValid)
            {
                // If model is not valid prioritiesDropDown will be null so we need do populated it.
                model.PrioritiesDropDown = this.mapper.Map<ICollection<BacklogPriorityDropDownModel>>
                    (await this.backlogPrioritiesService.GetAllAsync());

                return View(model);
            }

            var userStory = this.mapper.Map<UserStoryUpdateModel>(model.ViewModel);

            if (!string.IsNullOrWhiteSpace(model.Comment.Description))
            {
                var userId = int.Parse(HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value);
                userStory.Comment = model.Comment;
                userStory.Comment.UserStoryId = model.ViewModel.Id;
                userStory.Comment.AddedById = userId;
            }

            userStory.ProjectId = projectId;
            await this.userStoriesService.UpdateAsync(userStory);

            return RedirectToAction("Index", new { projectId = projectId });
        }
    }
}

src/Web/Views/UserStories/Create.cshtml
@model UserStoryInputModel

@{
    ViewData["Title"] = "Create";
    var priorities = Model.PrioritiesDropDown.Select(x => new SelectListItem() { Value = x.Id.ToString(), Text = x.Priority });
}

<script type="text/javascript" src="~/lib/tinymce/tinymce.min.js" asp-append-version="true"></script>
<script type="text/javascript" asp-append-version="true">
    tinyMCE.init({
        selector: '#textarea-tinemce',
        plugins: 'image paste table link code media lists',
        toolbar: `undo redo | numlist bullist styleselect | forecolor | bold italic | 
alignleft aligncenter alignright alignjustify | code`,
        themes: 'advanced',
        menubar: false,
        languages: 'en'
    });
</script>
<script type="text/javascript" asp-append-version="true">
    tinyMCE.init({
        selector: '#textarea-tinemce2',
        plugins: 'image paste table link code media lists',
        toolbar: `undo redo | numlist bullist styleselect | forecolor | bold italic | 
alignleft aligncenter alignright alignjustify | code`,
        themes: 'advanced',
        menubar: false,
        languages: 'en'
    });
</script>

<h4>Create User Story</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StoryPoints" class="control-label"></label>
                <input asp-for="StoryPoints" class="form-control" />
                <span asp-validation-for="StoryPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BacklogPriorityid" class="control-label"></label>
                <select asp-for="BacklogPriorityid" class="form-control"
                        asp-items="priorities"></select>
                <span asp-validation-for="BacklogPriorityid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea id="textarea-tinemce" asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AcceptanceCriteria" class="control-label"></label>
                <textarea id="textarea-tinemce2" asp-for="AcceptanceCriteria" class="form-control"></textarea>
                <span asp-validation-for="AcceptanceCriteria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/Web/Views/UserStories/Get.cshtml
@model UpdateUserStoriesViewModel;
@using Utilities.CalculateTimeAgo;

@{
    ViewData["Title"] = "User story Details";

    var priorities = Model.PrioritiesDropDown?
        .Select(x => new SelectListItem() { Value = x.Id.ToString(), Text = x.Priority });

    var commentsCounter = 0;
}

<link rel="stylesheet" href="~/css/UserStories/Get.css" asp-append-version="true" />
<script type="text/javascript" src="~/lib/tinymce/tinymce.min.js" asp-append-version="true"></script>
<script type="text/javascript" asp-append-version="true">
    tinyMCE.init({
        selector: '#textarea-tinemce-description',
        plugins: 'image paste table link code media lists',
        toolbar: `undo redo | numlist bullist styleselect | forecolor | bold italic |
alignleft aligncenter alignright alignjustify | code`,
        themes: 'advanced',
        menubar: false,
        languages: 'en',
        height: '480',
    });
</script>
<script type="text/javascript" asp-append-version="true">
    tinyMCE.init({
        selector: '#textarea-tinemce-acceptanceCriteria',
        plugins: 'image paste table link code media lists',
        toolbar: `undo redo | numlist bullist styleselect | forecolor | bold italic |
alignleft aligncenter alignright alignjustify | code`,
        themes: 'advanced',
        menubar: false,
        languages: 'en',
        height: '380',
    });
</script>
<script type="text/javascript" asp-append-version="true">
    tinyMCE.init({
        selector: '#textarea-tinemce-comment',
        plugins: 'image paste table link code media lists',
        toolbar: `undo redo | numlist bullist styleselect | forecolor | bold italic |
alignleft aligncenter alignright alignjustify | code`,
        themes: 'advanced',
        menubar: false,
        languages: 'en',
    });
</script>
<script type="text/javascript">
    function updateInputFromSelect(fromElId, toElId) {
        var e = document.getElementById(fromElId);
        var catSelected = e.options[e.selectedIndex].text;

        document.getElementById(toElId).value = catSelected;
    }
</script>

<div>
    <form method="post" asp-action="Get">
        <div asp-validation-summary="All" class="text-danger"></div>
        <span asp-validation-for="@Model.ViewModel.StoryPoints" class="text-danger"></span>
        <input asp-for="@Model.ViewModel.Id" hidden />
        <div class="left">
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">Id: @Model.ViewModel.Id</span>
                </div>
                <input type="text" class="form-control" asp-for="@Model.ViewModel.Title" aria-label="Title" aria-describedby="basic-addon1">
                <button class="btn btn-light" type="submit">Save and close</button>
            </div>
            <div class="small-flex">
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Story points</span>
                    </div>
                    <input type="text" class="form-control" asp-for="@Model.ViewModel.StoryPoints" aria-label="Title" aria-describedby="basic-addon1">
                </div>

                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">Story points</span>
                    </div>
                    <select asp-for="@Model.ViewModel.BacklogPriorityId" id="priorityInputSelect" onchange="updateInputFromSelect('priorityInputSelect', 'priorityInput');" class="form-control"
                            asp-items="priorities"></select>
                    <span asp-validation-for="@Model.ViewModel.BacklogPriorityPriority" class="text-danger"></span>
                </div>
            </div>
            <hr />

            <p class="text-info">Description</p>
            <textarea asp-for="@Model.ViewModel.Description" id="textarea-tinemce-description"> </textarea>
            <hr />

            <p class="text-info">Acceptance criteria</p>
            <textarea asp-for="@Model.ViewModel.AcceptanceCriteria" id="textarea-tinemce-acceptanceCriteria"></textarea>
            <span asp-validation-for="@Model.ViewModel.AcceptanceCriteria" class="text-danger"></span>

            <hr>
            <p class="text-info">Discussion</p>
            <p>Add comment</p>
            <textarea id="textarea-tinemce-comment" asp-for="Comment.Description"></textarea>
            <hr />
        </div>

        <div class="comments">
            @foreach (var comment in Model.ViewModel.Comments.OrderByDescending(x => x.AddedOn))
            {
                <div class="comment-header">
                    <div class="comment-header-text">
                        <div class="comment-header-details">
                            <p class="header-details-name">
                                @comment.AddedByEmail
                            </p>
                            <p class="header-detials-datestamp">
                                @CalculateTimeAgo.Calculate(comment.ModifiedOn ?? comment.AddedOn)
                            </p>
                        </div>

                        <div class="comment-header-buttons dropdown">
                            <a onclick="myFunction(@commentsCounter)" class="dropbtn">
                                <svg class="comment-menu-@commentsCounter" width="1.2rem" height="1.2rem" viewBox="0 0 16 16" class="bi bi-three-dots-vertical" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z" />
                                </svg>
                            </a>
                            <div id="myDropdown-@commentsCounter" class="dropdown-content edit-comment dropdown-content-@commentsCounter">
                                <a asp-action="Edit" asp-controller="Comments"
                                   asp-route-projectId="@this.ViewContext.RouteData.Values["projectId"]"
                                   asp-route-userStoryId="@comment.UserStoryId"
                                   asp-route-commentId="@comment.Id"
                                   id="edit-comment-a">
                                    Edit
                                </a>
                                <form method="post">
                                    <button class="del-button" type="submit" asp-action="Delete" asp-controller="Comments"
                                            asp-route-projectId="@this.ViewContext.RouteData.Values["projectId"]"
                                            asp-route-userStoryId="@comment.UserStoryId"
                                            asp-route-commentId="@comment.Id"
                                            id="del">
                                        Delete
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="comment-content">
                        @Html.Raw(@comment.SanitizedDescription)
                    </div>
                </div>
                <p hidden>
                    @(commentsCounter+= 1)
                </p>
            }
        </div>
    </form>
</div>

@section Scripts{
    <script src="~/js/UserStories/Get.js" asp-append-version="true"></script>
}

src/Web/Views/UserStories/Index.cshtml
@model IEnumerable<UserStoriesAllViewModel>
@using Shared.Constants;

@{
    ViewData["Title"] = "User stories overview";
}
<link rel="stylesheet" href="~/css/UserStories/Index.css" asp-append-version="true" />

<script src="~/js/UserStories/Index.js" asp-append-version="true"></script>
<div class="container">
    <div class="overflow-auto">
        <h2>User stories</h2>
        <nav class="navbar navbar-expand-sm navbar-expand-md navbar-expand-lg navbar-light bg-light" id="table-nav">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" asp-area="" asp-controller="UserStories"
                           asp-action="Create" asp-route-projectId="@this.ViewContext.RouteData.Values["projectId"]">
                            Add +
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <table class="table table-responsive-md table-bordered table-striped table-hover">
            <thead class="thead-light">
                <tr>
                    <th>
                        <div class="center-after-filter">
                            <div class="th-header">
                                <div class="th-header-title">
                                    Id
                                </div>
                                <div class="sorting">
                                    <a asp-route-sortingParams="@UserStoriesSortingConstants.IdDesc" class="sort-arrow">
                                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-up-short" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M8 12a.5.5 0 0 0 .5-.5V5.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 5.707V11.5a.5.5 0 0 0 .5.5z" />
                                        </svg>
                                    </a>
                                    <a asp-route-sortingParams="@UserStoriesSortingConstants.IdAsc" class="sort-arrow">
                                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-down-short" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L7.5 10.293V4.5A.5.5 0 0 1 8 4z" />
                                        </svg>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </th>
                    <th>
                        <div class="th-header">
                            <div class="th-header-title">
                                Title
                            </div>
                            <div class="sorting">
                                <a asp-route-sortingParams="@UserStoriesSortingConstants.TitleDesc" class="sort-arrow">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-up-short" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M8 12a.5.5 0 0 0 .5-.5V5.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 5.707V11.5a.5.5 0 0 0 .5.5z" />
                                    </svg>
                                </a>
                                <a asp-route-sortingParams="@UserStoriesSortingConstants.TitleAsc" class="sort-arrow">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-down-short" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L7.5 10.293V4.5A.5.5 0 0 1 8 4z" />
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </th>
                    <th>
                        <div class="th-header">
                            <div class="th-header-title">
                                Tasks Count
                            </div>
                            <div class="sorting">
                                <a asp-route-sortingParams="@UserStoriesSortingConstants.TasksCountDesc" class="sort-arrow">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-up-short" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M8 12a.5.5 0 0 0 .5-.5V5.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 5.707V11.5a.5.5 0 0 0 .5.5z" />
                                    </svg>
                                </a>
                                <a asp-route-sortingParams="@UserStoriesSortingConstants.TasksCountAsc" class="sort-arrow">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-down-short" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L7.5 10.293V4.5A.5.5 0 0 1 8 4z" />
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </th>
                    <th>
                        <div class="th-header">
                            <div class="th-header-title">
                                Story Points
                            </div>
                            <div class="sorting">
                                <a asp-route-sortingParams="@UserStoriesSortingConstants.StoryPointsDesc" class="sort-arrow">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-up-short" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M8 12a.5.5 0 0 0 .5-.5V5.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 5.707V11.5a.5.5 0 0 0 .5.5z" />
                                    </svg>
                                </a>
                                <a asp-route-sortingParams="@UserStoriesSortingConstants.StoryPointsAsc" class="sort-arrow">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-down-short" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L7.5 10.293V4.5A.5.5 0 0 1 8 4z" />
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </th>
                    <th>
                        <div class="th-header">
                            <div class="th-header-title">
                                Priority
                            </div>
                            <div class="sorting">
                                <a asp-route-sortingParams="@UserStoriesSortingConstants.PriorityDesc" class="sort-arrow">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-up-short" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M8 12a.5.5 0 0 0 .5-.5V5.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 5.707V11.5a.5.5 0 0 0 .5.5z" />
                                    </svg>
                                </a>
                                <a asp-route-sortingParams="@UserStoriesSortingConstants.PriorityAsc" class="sort-arrow">
                                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-down-short" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L7.5 10.293V4.5A.5.5 0 0 1 8 4z" />
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var userStory in Model)
                {
                    <tr>
                        <td>@userStory.Id</td>
                        <td>@userStory.Title</td>
                        <td>@userStory.TasksCount</td>
                        <td>@userStory.StoryPoints</td>
                        <td>@userStory.BacklogPriorityPriority</td>
                        <td>
                            <a asp-action="Get" 
                               asp-route-userStoryId="@userStory.Id" 
                               asp-route-projectId="@this.ViewContext.RouteData.Values["projectId"]" 
                               class="btn btn-sm btn-info">
                                Edit
                            </a>
                            <form method="post" style="display:inline-block;" 
                                   asp-action="Delete"
                                   asp-route-userStoryId="@userStory.Id"
                                   asp-route-projectId="@this.ViewContext.RouteData.Values["projectId"]">
                                <button type="submit" 
                                   class="btn btn-sm btn-danger" id="del">
                                    Delete
                                </button>
                            </form>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>